name: paco-anthos

credentials:
  ansible_user: tc
  ansible_ssh_private_key_file: /home/tc/.ssh/id_rsa
  ansible_ssh_extra_args: "-o IdentitiesOnly=yes"

cluster:
  kind: anthos
  region: europe-west1
  anthos_dir: baremetal
  anthos_version: 1.9.1
  project_id: anthos-bm-nokia
  cluster_name: telcocloud-cluster
  networks:
    pod: {ipv4_cidr: [172.17.0.0/16]}
    svc: {ipv4_cidr: [172.16.0.0/16]}

container_registry:
  kind: harbor
  name: paco-harbor
  url: 'https://harbor.nokia.cloudpj.be/chartrepo/paco'
  server: 'harbor.nokia.cloudpj.be'
  image_dir: paco
  email: robot@harbor.nokia.cloudpj.be
  username: robot$paco
  secret: xxx

infrastructure:
  internet_dns: 8.8.8.8
  # dual-stack, ipv4-only, ipv6-only
  addressing_schema: "dual-stack"
  networks:
    loopback: {ipv4_cidr: [100.112.100.0/24], ipv6_cidr: [3100:100::/48]}
    isl: {ipv4_cidr: [100.64.0.0/16], ipv6_cidr: [3100:64::/48], ipv4_itfce_prefix_length: 31, ipv6_itfce_prefix_length: 127}
    loop: {ipv4_cidr: [100.99.0.0/24], ipv6_cidr: [3100:65::/64], ipv4_itfce_prefix_length: 31, ipv6_itfce_prefix_length: 127}
  protocols:
    protocol: ebgp
    as_pool: [65000, 65100]
    as_pool_loop: [65902, 65903]
    overlay_as: 65002
    overlay_protocol: evpn

workloads:
  provisioning:
    servers:
      itfces:
        itfce: {vlan_id: 0, kind: bridged}
  infrastructure:
    servers:
      itfces:
        itfce: {vlan_id: 1020, kind: irb, ipv4_cidr: [10.101.12.0/26], ipv6_cidr: [2a02:1800:80:7000::/64],}
    dcgw-grp1:
      itfces:
        itfce: {vlan_id: 1040, peer_as: 65910, kind: routed, ipv4_cidr: [10.100.40.0/24], ipv6_cidr: [2a02:1800:80:7050::/64], ipv4_itfce_prefix_length: 31, ipv6_itfce_prefix_length: 127, addressing_schema: "dual-stack"}
  multus-mgmt:
    servers:
      itfces:
        ipvlan: {vlan_id: 1200, kind: irb, ipv4_cidr: [10.0.20.0/24], ipv6_cidr: [2a02:1800:80:7200::/64]}
        sriov1.1: {vlan_id: 1210, kind: irb, ipv4_cidr: [10.0.21.0/27, 10.0.21.32/27, 10.0.21.64/27, 10.0.21.96/27, 10.0.21.128/27, 10.0.21.160/27], ipv6_cidr: [2a02:1800:80:7210::/64, 2a02:1800:80:7211::/64, 2a02:1800:80:7212::/64, 2a02:1800:80:7213::/64, 2a02:1800:80:7214::/64, 2a02:1800:80:7215::/64], target: leaf1}
        sriov2.1: {vlan_id: 1220, kind: irb, ipv4_cidr: [10.0.22.0/27, 10.0.22.32/27, 10.0.22.64/27, 10.0.22.96/27, 10.0.22.128/27, 10.0.22.160/27], ipv6_cidr: [2a02:1800:80:7220::/64, 2a02:1800:80:7221::/64, 2a02:1800:80:7222::/64, 2a02:1800:80:7223::/64, 2a02:1800:80:7224::/64, 2a02:1800:80:7225::/64], target: leaf2}
    dcgw-grp1:
      itfces:
        itfce: {vlan_id: 1250, peer_as: 65912, kind: routed, ipv4_cidr: [10.0.26.0/24], ipv6_cidr: [2a02:1800:80:7260::/64], ipv4_itfce_prefix_length: 31, ipv6_itfce_prefix_length: 127, addressing_schema: "dual-stack"}
  multus-internal:
    servers:
      itfces:
        ipvlan: {vlan_id: 1300, kind: irb, ipv4_cidr: [10.0.30.0/24], ipv6_cidr: [2a02:1800:80:7300::/64]}
        sriov1.1: {vlan_id: 1310, kind: irb, ipv4_cidr: [10.0.31.0/27, 10.0.31.32/27, 10.0.31.64/27, 10.0.31.96/27, 10.0.31.128/27, 10.0.31.160/27], ipv6_cidr: [2a02:1800:80:7310::/64, 2a02:1800:80:7311::/64, 2a02:1800:80:7312::/64, 2a02:1800:80:7313::/64, 2a02:1800:80:7314::/64, 2a02:1800:80:7315::/64], target: leaf1}
        sriov2.1: {vlan_id: 1320, kind: irb, ipv4_cidr: [10.0.32.0/27, 10.0.32.32/27, 10.0.32.64/27, 10.0.32.96/27, 10.0.32.128/27, 10.0.32.160/27], ipv6_cidr: [2a02:1800:80:7320::/64, 2a02:1800:80:7321::/64, 2a02:1800:80:7322::/64, 2a02:1800:80:7323::/64, 2a02:1800:80:7324::/64, 2a02:1800:80:7325::/64], target: leaf2}
      loopbacks:
        loopback: {idx: 1350, ipv4_cidr: [10.0.35.0/24], ipv6_cidr: [2a02:1800:80:7350::/64]}
    dcgw-grp1:
      itfces:
        itfce: {vlan_id: 1350, peer_as: 65913, kind: routed, ipv4_cidr: [10.0.36.0/24], ipv6_cidr: [2a02:1800:80:7360::/64], ipv4_itfce_prefix_length: 31, ipv6_itfce_prefix_length: 127, addressing_schema: "dual-stack"}
  multus-external:
    servers:
      itfces:
        ipvlan: {vlan_id: 1400, kind: irb, ipv4_cidr: [10.0.40.0/24], ipv6_cidr: [2a02:1800:80:7400::/64]}
        sriov1.1: {vlan_id: 1410, kind: irb, ipv4_cidr: [10.0.41.0/27, 10.0.41.32/27, 10.0.41.64/27, 10.0.41.96/27, 10.0.41.128/27, 10.0.41.160/27], ipv6_cidr: [2a02:1800:80:7410::/64, 2a02:1800:80:7411::/64, 2a02:1800:80:7412::/64, 2a02:1800:80:7413::/64, 2a02:1800:80:7414::/64, 2a02:1800:80:7415::/64], target: leaf1}
        sriov2.1: {vlan_id: 1420, kind: irb, ipv4_cidr: [10.0.42.0/27, 10.0.42.32/27, 10.0.42.64/27, 10.0.42.96/27, 10.0.42.128/27, 10.0.42.160/27], ipv6_cidr: [2a02:1800:80:7420::/64, 2a02:1800:80:7421::/64, 2a02:1800:80:7422::/64, 2a02:1800:80:7423::/64, 2a02:1800:80:7424::/64, 2a02:1800:80:7425::/64], target: leaf2}
      loopbacks:
       loopback: {idx: 1450, ipv4_cidr: [10.0.45.0/24], ipv6_cidr: [2a02:1800:80:7450::/64]}
    dcgw-grp1:
      itfces:
        itfce: {vlan_id: 1450, peer_as: 65914, kind: routed, ipv4_cidr: [10.1.46.0/24], ipv6_cidr: [2a02:1800:80:7460::/64], ipv4_itfce_prefix_length: 31, ipv6_itfce_prefix_length: 127, addressing_schema: "dual-stack"}
  multus-sba:
    servers:
      itfces:
        ipvlan: {vlan_id: 1100, kind: irb, ipv4_cidr: [10.0.10.0/24], ipv6_cidr: [2a02:1800:80:7100::/64]}
        sriov1.1: {vlan_id: 1110, kind: irb, ipv4_cidr: [10.0.11.0/27, 10.0.11.32/27, 10.0.11.64/27, 10.0.11.96/27, 10.0.11.128/27, 10.0.11.160/27], ipv6_cidr: [2a02:1800:80:7110::/64, 2a02:1800:80:7111::/64, 2a02:1800:80:7112::/64, 2a02:1800:80:7113::/64, 2a02:1800:80:7114::/64, 2a02:1800:80:7115::/64], target: leaf1}
        sriov2.1: {vlan_id: 1120, kind: irb, ipv4_cidr: [10.0.12.0/27, 10.0.12.32/27, 10.0.12.64/27, 10.0.12.96/27, 10.0.12.128/27, 10.0.12.160/27], ipv6_cidr: [2a02:1800:80:7120::/64, 2a02:1800:80:7121::/64, 2a02:1800:80:7122::/64, 2a02:1800:80:7123::/64, 2a02:1800:80:7124::/64, 2a02:1800:80:7125::/64], target: leaf2}
      loopbacks:
       loopback: {idx: 1150, ipv4_cidr: [10.0.15.0/24], ipv6_cidr: [2a02:1800:80:7150::/64]}
    dcgw-grp1:
      itfces:
        itfce: {vlan_id: 1150, peer_as: 65911, kind: routed, ipv4_cidr: [10.0.16.0/24], ipv6_cidr: [2a02:1800:80:7160::/64], ipv4_itfce_prefix_length: 31, ipv6_itfce_prefix_length: 127, addressing_schema: "dual-stack"}
  multus-internet:
    servers:
      itfces:
        ipvlan: {vlan_id: 1500, kind: irb, ipv4_cidr: [10.0.50.0/24], ipv6_cidr: [2a02:1800:80:7500::/64]}
        sriov1.1: {vlan_id: 1510, kind: irb, ipv4_cidr: [10.0.51.0/27, 10.0.51.32/27, 10.0.51.64/27, 10.0.51.96/27, 10.0.51.128/27, 10.0.51.160/27], ipv6_cidr: [2a02:1800:80:7510::/64, 2a02:1800:80:7511::/64, 2a02:1800:80:7512::/64, 2a02:1800:80:7513::/64, 2a02:1800:80:7514::/64, 2a02:1800:80:7515::/64], target: leaf1}
        sriov2.1: {vlan_id: 1520, kind: irb, ipv4_cidr: [10.0.52.0/27, 10.0.52.32/27, 10.0.52.64/27, 10.0.52.96/27, 10.0.52.128/27, 10.0.52.160/27], ipv6_cidr: [2a02:1800:80:7520::/64, 2a02:1800:80:7521::/64, 2a02:1800:80:7522::/64, 2a02:1800:80:7523::/64, 2a02:1800:80:7524::/64, 2a02:1800:80:7525::/64], target: leaf2}
      loopbacks:
        loopback: {idx: 1550, ipv4_cidr: [10.0.55.0/24], ipv6_cidr: [2a02:1800:80:7550::/64]}
    dcgw-grp1:
      itfces:
        itfce: {vlan_id: 1550, peer_as: 65915, kind: routed, ipv4_cidr: [10.0.56.0/24], ipv6_cidr: [2a02:1800:80:7560::/64], ipv4_itfce_prefix_length: 31, ipv6_itfce_prefix_length: 127, addressing_schema: "dual-stack"}
  multus-enterprise:
    servers:
      itfces:
        ipvlan: {vlan_id: 1600, kind: irb, ipv4_cidr: [10.0.60.0/24], ipv6_cidr: [2a02:1800:80:7600::/64]}
        sriov1.1: {vlan_id: 1610, kind: irb, ipv4_cidr: [10.0.61.0/27, 10.0.61.32/27, 10.0.51.64/27, 10.0.61.96/27, 10.0.61.128/27, 10.0.61.160/27], ipv6_cidr: [2a02:1800:80:7610::/64, 2a02:1800:80:7611::/64, 2a02:1800:80:7612::/64, 2a02:1800:80:7613::/64, 2a02:1800:80:7614::/64, 2a02:1800:80:7615::/64], target: leaf1}
        sriov2.1: {vlan_id: 1620, kind: irb, ipv4_cidr: [10.0.62.0/27, 10.0.62.32/27, 10.0.52.64/27, 10.0.62.96/27, 10.0.62.128/27, 10.0.62.160/27], ipv6_cidr: [2a02:1800:80:7620::/64, 2a02:1800:80:7621::/64, 2a02:1800:80:7622::/64, 2a02:1800:80:7623::/64, 2a02:1800:80:7624::/64, 2a02:1800:80:7625::/64], target: leaf2}
      loopbacks:
        loopback: {idx: 1650, ipv4_cidr: [10.0.65.0/24], ipv6_cidr: [2a02:1800:80:7650::/64]}
    dcgw-grp1:
      itfces:
        itfce: {vlan_id: 1650, peer_as: 65916, kind: routed, ipv4_cidr: [10.0.66.0/24], ipv6_cidr: [2a02:1800:80:7560::/64], ipv4_itfce_prefix_length: 31, ipv6_itfce_prefix_length: 127, addressing_schema: "dual-stack"}

appnetwindexes:
  itfce:
    switch:
      gw: 1
    smf:
      int: 160
      llb: 2
    upf:
      int: 170
      llb: 3
      # allocates from 4..19 in a ntok model
      # for ntok only 1 subnet is used, for 1to1 2 subnets are used
      lmg: 4
    amf:
      # allocates 4 addresses
      int: 151
      fip: 200
  loopback:
    # one per switch
    switch: 
      # [1..2] allocated one per switch
      bgp: 1
    smf:
      system:  23
      bgp: 3
      # [31..36] allocates max 6 (UPF/SMF LLB pods per CNF)
      llb-pod: 31
      llb-sig: 103
    upf:
      system:  24
      bgp: 4
      # [41..46] allocates max 6 (UPF/SMF LLB pods per CNF)
      llb-pod: 41
      llb-sig: 104
      # [51..66] max. 16 (UPF LMG pods per CNF)
      lmg-pod: 51
      # [71..86] max. 16 (UPF LMG pods per CNF)
      lmg-sig: 71
    amf:
      sig: 105

application:
  paco:
    global:
      multus: 
        3GPP_SBA: {wl-name: multus-sba, vrfcp-id: 17001, vrfup-id: 1000}
        oam: {wl-name: multus-mgmt, vrfcp-id: 17002, vrfup-id: 2000}
        3GPP_Internal: {wl-name: multus-internal, vrfcp-id: 17003, vrfup-id: 3000}
        3GPP_External: {wl-name: multus-external, vrfcp-id: 17004, vrfup-id: 4000}
        3GPP_Internet: {wl-name: multus-internet, vrfcp-id: 17005, vrfup-id: 5000}
    deployment:
      #multiNet, vlanAwareApp
      connectivitymode: multiNet 
      networkname: NokiaDemo
      networkshortname: NOKIA
      nat: true
      sigrefpoints: 10.100.11.2/24
      apn: demo.nokia
      uepoolcidr: 100.64.0.0/16
      supi: 
      - ["234100000000000", "234100200000000"]
      - ["234100300000000", "234100400000000"]
      plmn: {mcc: 234, mnc: 100}
      dnn: [demo.nokia.mnc100.mcc234.gprs, test.demo.nokia.mnc100.mcc234.gprs]
      tac: [1, 2, 9999, 3111, 3112, 3113, 3114]
      slices:
        sst1: {value: 1, diff: [sd1: ABCDEF, sd2: XCVGHI]}
        sst2: {value: 2, diff: [sd3: AAAAAA]}
    cnfs: 
      upf:
        host_device: bond0
        deployment: ntok
        k: 1
        enabled: true
        namespace: upf
        networking: 
          as: 65003
          # we assume the internal is always present since we take system IP from there
          multus: 
            oam: {wl-name: multus-mgmt, type: ipvlan}
            3GPP_Internal: {wl-name: multus-internal, type: sriov}
            3GPP_External: {wl-name: multus-external, type: sriov}
            3GPP_Internet: {wl-name: multus-internet, type: sriov}
        pods:
          loam: {tag: B-12.0.R5-1, cpu: 4, memory: 8Gi, enabled: true }
          lmg: {tag: B-12.0.R5-1, cpu: 8, memory: 16Gi, hugepages1Gi: 1Gi, nodeSelector: "{}", enabled: true, total: 3, numa: 0}
          llb: {tag: B-12.0.R5-1, cpu: 6, memory: 16Gi, hugepages1Gi: 1Gi, nodeSelector: "{}", enabled: true, total: 2, numa: 0}
          nasc: {tag: B-12.0.R5-1, cpu: 1, memory: 16Gi, enabled: true}
          logging: {tag: B-12.0.R5-1, cpu: 1, memory: 1Gi, enabled: true}
          awsSideCar: {tag: B-12.0.R5-1, cpu: 100m, memory: 100Mi, enabled: false}
      smf:
        host_device: bond0
        enabled: true
        namespace: smf
        networking: 
          as: 65002
          # we assume the internal is always present since we take system IP from there
          multus:
            oam: {wl-name: multus-mgmt, type: ipvlan}
            3GPP_Internal: {wl-name: multus-internal, type: sriov}
            3GPP_SBA: {wl-name: multus-sba, type: sriov}
        pods:
          loam: {tag: B-12.0.R5-1, cpu: 4, memory: 8Gi, enabled: true}
          lmg: {tag: B-12.0.R5-1, cpu: 8, memory: 16Gi, hugepages1Gi: 1Gi, nodeSelector: "{}", enabled: false}
          llb: {tag: B-12.0.R5-1, cpu: 6, memory: 16Gi, hugepages1Gi: 1Gi, nodeSelector: "{}", enabled: true, total: 2, numa: 0}
          nasc: {tag: B-12.0.R5-1, cpu: 1, memory: 1Gi, enabled: true}
          logging: {tag: B-12.0.R5-1, cpu: 1, memory: 1Gi, enabled: true}
          awsSideCar: {tag: B-12.0.R5-1, cpu: 100m, memory: 100Mi, enabled: false}
      amf:
        host_device: bond0
        enabled: true
        namespace: amf
        storage_class: manual
        prometheus_ip: 192.168.5.14
        networking: 
          # oam is mandatory, other networks can be renamed or deleted/added
          multus:
            oam: {wl-name: multus-mgmt, type: ipvlan}
            3GPP_External: {wl-name: multus-external,  type: ipvlan}
            3GPP_SBA: {wl-name: multus-sba,  type: ipvlan}
        pods:
          dbs: {tag: CMM21.0.0P1, cpu: 4, memory: 8Gi, nodeSelector: "{}", antiaffinity: [dbs], initialDelaySeconds: 15, periodSeconds: 20, enabled: true}
          emms_amms: {tag: CMM21.0.0P1, cpu: 4, memory: 16Gi, nodeSelector: "{}", antiaffinity: [amms], initialDelaySeconds: 5, periodSeconds: 20, enabled: true}
          ipds: {tag: CMM21.0.0P1, cpu: 6, memory: 12Gi, nodeSelector: "{}", antiaffinity: [ipds], initialDelaySeconds: 30, periodSeconds: 20, enabled: true}
          ipps: {tag: CMM21.0.0P1, cpu: 8, memory: 12Gi, nodeSelector: "{}", antiaffinity: [], initialDelaySeconds: 30, periodSeconds: 20, enabled: false}
          necc: {tag: CMM21.0.0P1, cpu: 4, memory: 12Gi, nodeSelector: "{}", antiaffinity: [necc], initialDelaySeconds: 120, periodSeconds: 20, enabled: true}
          paps: {tag: CMM21.0.0P1, cpu: 4, memory: 12Gi, nodeSelector: "{}", antiaffinity: [], initialDelaySeconds: 30, periodSeconds: 20, enabled: false}

topology:
  kinds:
    srl:
      type: ixrd2
      position: network
    vr-sros:
      type: sr-1s
      position: network
    linux:
      type: rhel8
      labels: {"need_update_dist": false, "install_rt_sched": false, "install_net_driver": true} 
      position: access
      storage:
        nfs_server: 100.112.1.201
        nfs_mount: /nfs
        csi: nfs-csi
  nodes:
    leaf1:
      kind: srl
      mgmt_ipv4: 172.20.20.3
      labels: {"target": "leaf-grp1"}
      as: 4259845498      
    leaf2:
      kind: srl
      mgmt_ipv4: 172.20.20.4
      labels: {"target": "leaf-grp1"}
      as: 4259845498
    master0:
      kind: linux
      mgmt_ipv4: 100.112.3.11
      labels: {"target": "servers"}
    worker0:
      kind: linux
      mgmt_ipv4: 100.112.3.12
      labels: {"target": "servers"}
    worker1:
      kind: linux
      mgmt_ipv4: 100.112.3.13
      labels: {"target": "servers"}
    worker2:
      kind: linux
      mgmt_ipv4: 100.112.3.14
      labels: {"target": "servers"}
    worker3:
      kind: linux
      mgmt_ipv4: 100.112.3.15
      labels: {"target": "servers"}
    dcgw1:
      kind: sros
      mgmt_ipv4: 172.20.20.1
      labels: {"target": "dcgw-grp1"}
    dcgw2:
      kind: sros
      mgmt_ipv4: 172.20.20.2
      labels: {"target": "dcgw-grp1"}
  links:
    # server connectivity
    - endpoints: ["leaf1:e1-1", "master0:ens5f0"]
      labels: {"kind": "access", "type": "esi1", "client-name": "bond0", "sriov": true, "ipvlan": true, "speed": "10G", "pxe": true, "numa": 0}
    - endpoints: ["leaf2:e1-1", "master0:ens5f1"]
      labels: {"kind": "access", "type": "esi1", "client-name": "bond0", "sriov": true, "ipvlan": true, "speed": "10G", "numa": 0}
    # - endpoints: ["leaf1:e1-3", "worker0:eno5"]
    #   labels: {"kind": "access", "type": "esi3", "client-name": "bond0", "sriov": true, "ipvlan": true, "speed": "10G", "pxe": true}
    # - endpoints: ["leaf2:e1-3", "worker0:eno6"]
    #   labels: {"kind": "access", "type": "esi3", "client-name": "bond0", "sriov": true, "ipvlan": true, "speed": "10G"}
    # - endpoints: ["leaf1:e1-4", "worker0:ens2f0"]
    #   labels: {"kind": "access", "type": "esi4", "client-name": "bond1", "sriov": true, "ipvlan": true, "speed": "10G", "pxe": true}
    # - endpoints: ["leaf2:e1-4", "worker0:ens2f1"]
    #   labels: {"kind": "access", "type": "esi4", "client-name": "bond1", "sriov": true, "ipvlan": true, "speed": "10G"}
    # - endpoints: ["leaf1:e1-5", "worker1:eno5"]
    #   labels: {"kind": "access", "type": "esi5", "client-name": "bond0", "sriov": true, "ipvlan": true, "speed": "10G", "pxe": true}
    # - endpoints: ["leaf2:e1-5", "worker1:eno6"]
    #   labels: {"kind": "access", "type": "esi5", "client-name": "bond0", "sriov": true, "ipvlan": true, "speed": "10G"}
    # - endpoints: ["leaf1:e1-6", "worker1:ens2f0"]
    #   labels: {"kind": "access", "type": "esi6", "client-name": "bond1", "sriov": true, "ipvlan": true, "speed": "10G", "pxe": true}
    # - endpoints: ["leaf2:e1-6", "worker1:ens2f1"]
    #   labels: {"kind": "access", "type": "esi6", "client-name": "bond1", "sriov": true, "ipvlan": true, "speed": "10G"}
    # - endpoints: ["leaf1:e1-7", "worker2:eno5"]
    #   labels: {"kind": "access", "type": "esi7", "client-name": "bond0", "sriov": true, "ipvlan": true, "speed": "10G", "pxe": true}
    # - endpoints: ["leaf2:e1-7", "worker2:eno6"]
    #   labels: {"kind": "access", "type": "esi7", "client-name": "bond0", "sriov": true, "ipvlan": true, "speed": "10G"}
    # - endpoints: ["leaf1:e1-8", "worker2:ens2f0"]
    #   labels: {"kind": "access", "type": "esi8", "client-name": "bond1", "sriov": true, "ipvlan": true, "speed": "10G", "pxe": true}
    # - endpoints: ["leaf2:e1-8", "worker2:ens2f1"]
    #   labels: {"kind": "access", "type": "esi8", "client-name": "bond1", "sriov": true, "ipvlan": true, "speed": "10G"}
    # - endpoints: ["leaf1:e1-9", "worker3:eno5"]
    #   labels: {"kind": "access", "type": "esi9", "client-name": "bond0", "sriov": true, "ipvlan": true, "speed": "10G", "pxe": true}
    # - endpoints: ["leaf2:e1-9", "worker3:eno6"]
    #   labels: {"kind": "access", "type": "esi9", "client-name": "bond0", "sriov": true, "ipvlan": true, "speed": "10G"}
    # - endpoints: ["leaf1:e1-10", "worker3:ens2f0"]
    #   labels: {"kind": "access", "type": "esi10", "client-name": "bond1", "sriov": true, "ipvlan": true, "speed": "10G", "pxe": true}
    # - endpoints: ["leaf2:e1-10", "worker3:ens2f1"]
    #   labels: {"kind": "access", "type": "esi10", "client-name": "bond1", "sriov": true, "ipvlan": true, "speed": "10G"}
    # switch interconnect links
    - endpoints: ["leaf1:e1-49", "leaf2:e1-49"]
    - endpoints: ["leaf1:e1-47", "leaf1:e1-48"]
      labels: {"kind": "loop", "speed": "40G"}
    - endpoints: ["leaf2:e1-47", "leaf2:e1-48"]
      labels: {"kind": "loop", "speed": "40G"}
    # dcgw connectivity
    - endpoints: ["leaf1:e1-50", "dcgw1:eth1"]
      labels: {"kind": "gw", "speed": "40G"}
    - endpoints: ["leaf2:e1-50", "dcgw2:eth1"]
      labels: {"kind": "gw", "speed": "40G"}

