name: paco-anthos

credentials:
  ansible_user: nokia
  ansible_ssh_private_key_file: /home/nokia/.ssh/id_rsa
  ansible_ssh_extra_args: "-o IdentitiesOnly=yes"

cluster:
  kind: anthos
  region: europe-west1
  anthos_dir: baremetal
  anthos_version: 1.7.0
  project_id: anthos-bm-nokia
  cluster_name: telco-paco-cluster
  networks:
    pod: {ipv4_cidr: 192.168.0.0/16}
    svc: {ipv4_cidr: 10.96.0.0/12}

container_registry:
  kind: harbor
  name: paco-harbor
  url: 'https://harbor.nokia.cloudpj.be/chartrepo/paco'
  server: 'harbor.nokia.cloudpj.be'
  image_dir: paco
  email: robot@harbor.nokia.cloudpj.be
  username: robot$paco
  secret: xxx

infrastructure:
  internet_dns: 8.8.8.8
  # dual-stack, ipv4-only, ipv6-only
  addressing_schema: "dual-stack"
  networks:
    loopback: {ipv4_cidr: 100.112.100.0/24, ipv6_cidr: 3100:100::/48}
    isl: {ipv4_cidr: 100.64.0.0/16, ipv6_cidr: 3100:64::/48, ipv4_itfce_prefix_length: 31, ipv6_itfce_prefix_length: 127}
  protocols:
    protocol: ebgp
    as_pool: [65000, 65100]
    overlay_as: 65002
    overlay_protocol: evpn

workloads:
  provisioning:
    servers:
      vlans:
        itfce: {vlan_id: 0, kind: bridged}
  infrastructure:
    servers:
      vlans:
        itfce: {vlan_id: 40, kind: irb, ipv4_cidr: 100.112.3.11/24, ipv6_cidr: 2010:100:3::/64,}
    dcgw-grp1:
      vlans:
        itfce: {vlan_id: 45, kind: routed, ipv4_cidr: 10.100.40.0/24, ipv6_cidr: 2010:100:40::/48, ipv4_itfce_prefix_length: 31, ipv6_itfce_prefix_length: 127, addressing_schema: "dual-stack"}
  multus-mgmt:
    servers:
      vlans:
        ipvlan: {vlan_id: 101, kind: irb, ipv4_cidr: 10.1.11.0/24, ipv6_cidr: 2010:100:11::/64,}
        sriov1: {vlan_id: 102, kind: irb, ipv4_cidr: 10.1.12.0/24, ipv6_cidr: 2010:100:12::/64, target: leaf1}
        sriov2: {vlan_id: 103, kind: irb, ipv4_cidr: 10.1.13.0/24, ipv6_cidr: 2010:100:13::/64, target: leaf2}
      networks:
        loopback: {ipv4_cidr: 10.254.15.0/24}
    dcgw-grp1:
      vlans:
        itfce: {vlan_id: 105, kind: routed, ipv4_cidr: 10.100.15.0/24, ipv6_cidr: 2010:100:15::/48, ipv4_itfce_prefix_length: 31, ipv6_itfce_prefix_length: 127, addressing_schema: "dual-stack"}
  multus-internal:
    servers:
      vlans:
        ipvlan: {vlan_id: 201, kind: irb, ipv4_cidr: 10.1.21.0/24, ipv6_cidr: 2010:100:21::/64}
        sriov1: {vlan_id: 202, kind: irb, ipv4_cidr: 10.1.22.0/24, ipv6_cidr: 2010:100:22::/64, target: leaf1}
        sriov2: {vlan_id: 203, kind: irb, ipv4_cidr: 10.1.23.0/24, ipv6_cidr: 2010:100:23::/64, target: leaf2}
      networks:
        loopback: {ipv4_cidr: 10.254.25.0/24}
    dcgw-grp1:
      vlans:
        itfce: {vlan_id: 205, kind: routed, ipv4_cidr: 10.100.25.0/24, ipv6_cidr: 2010:100:25::/48, ipv4_itfce_prefix_length: 31, ipv6_itfce_prefix_length: 127, addressing_schema: "dual-stack"}
  multus-external:
    servers:
      vlans:
        ipvlan: {vlan_id: 301, kind: irb, ipv4_cidr: 10.1.31.0/24, ipv6_cidr: 2010:100:31::/64}
        sriov1: {vlan_id: 302, kind: irb, ipv4_cidr: 10.1.32.0/24, ipv6_cidr: 2010:100:32::/64, target: leaf1}
        sriov2: {vlan_id: 303, kind: irb, ipv4_cidr: 10.1.33.0/24, ipv6_cidr: 2010:100:33::/64, target: leaf2}
      networks:
       loopback: {ipv4_cidr: 10.254.35.0/24}
    dcgw-grp1:
      vlans:
        itfce: {vlan_id: 305, kind: routed, ipv4_cidr: 10.100.35.0/24, ipv6_cidr: 2010:100:35::/48, ipv4_itfce_prefix_length: 31, ipv6_itfce_prefix_length: 127, addressing_schema: "dual-stack"}
  multus-sba:
    servers:
      vlans:
        ipvlan: {vlan_id: 401, kind: irb, ipv4_cidr: 10.1.41.0/24, ipv6_cidr: 2010:100:41::/64}
        sriov1: {vlan_id: 402, kind: irb, ipv4_cidr: 10.1.42.0/24, ipv6_cidr: 2010:100:42::/64, target: leaf1}
        sriov2: {vlan_id: 403, kind: irb, ipv4_cidr: 10.1.43.0/24, ipv6_cidr: 2010:100:43::/64, target: leaf2}
      networks:
       loopback: {ipv4_cidr: 10.254.45.0/24}
    dcgw-grp1:
      vlans:
        itfce: {vlan_id: 405, kind: routed, ipv4_cidr: 10.100.45.0/24, ipv6_cidr: 2010:100:45::/48, ipv4_itfce_prefix_length: 31, ipv6_itfce_prefix_length: 127, addressing_schema: "dual-stack"}
  multus-internet:
    servers:
      vlans:
        ipvlan: {vlan_id: 501, kind: irb, ipv4_cidr: 10.1.51.0/24, ipv6_cidr: 2010:100:51::/64}
        sriov1: {vlan_id: 502, kind: irb, ipv4_cidr: 10.1.52.0/24, ipv6_cidr: 2010:100:52::/64, target: leaf1}
        sriov2: {vlan_id: 503, kind: irb, ipv4_cidr: 10.1.53.0/24, ipv6_cidr: 2010:100:53::/64, target: leaf2}
      networks:
        loopback: {ipv4_cidr: 10.254.55.0/24}
    dcgw-grp1:
      vlans:
        itfce: {vlan_id: 505, kind: routed, ipv4_cidr: 10.100.55.0/24, ipv6_cidr: 2010:100:55::/48, ipv4_itfce_prefix_length: 31, ipv6_itfce_prefix_length: 127, addressing_schema: "dual-stack"}

application:
  paco:
    deployment:
      networkname: NokiaDemo
      networkshortname: NOKIA
      nat: true
      sigrefpoints: 10.100.11.2/24
      uepoolcidr: 10.0.128.0/17
      supi: 
      - ["234100000000000", "234100200000000"]
      - ["234100000000000", "234100200000000"]
      plmn: {mcc: 234, mnc: 10}
      dnn: [demo.nokia.mnc100.mcc234.gprs, test.demo.nokia.mnc100.mcc234.gprs]
      tac: [1, 2, 9999, 3111, 3112, 3113, 3114]
      slices:
        sst1: {value: 1, diff: [sd1: ABCDEF, sd2: XCVGH]}
        sst2: {value: 2, diff: [sd3: AAAAAA]}
    cnfs: 
      upf:
        enabled: true
        namespace: upf
        networking: 
          type: sriov
          multus: {external: multus_external, internal: multus_internal, internet: multus_internet}
        pods:
          loam: {tag: B-12.0.R7, cpu: 4, memory: 8Gi, nodeSelector: "{}", enabled: true }
          lmg: {tag: B-12.0.R7, cpu: 8, memory: 16Gi, hugepages1Gi: 1Gi, nodeSelector: "{}", enabled: true}
          llb: {tag: B-12.0.R7, cpu: 6, memory: 16Gi, hugepages1Gi: 1Gi, nodeSelector: "{}", enabled: false, total: 3}
          nasc: {tag: B-12.0.R7, cpu: 1, memory: 16Gi, enabled: true}
          logging: {tag: B-12.0.R7, cpu: 1, memory: 1Gi, enabled: true}
          awsSideCar: {tag: B-12.0.R7, cpu: 100m, memory: 100Mi, enabled: false}
      smf:
        enabled: true
        namespace: smf
        networking: 
          type: sriov
          multus: {external: multus_external, internal: multus_internal}
        pods:
          loam: {tag: B-12.0.R7, cpu: 4, memory: 4Gi, nodeSelector: "{}", enabled: true}
          lmg: {tag: B-12.0.R7, cpu: 6, memory: 16Gi, hugepages1Gi: 1Gi, nodeSelector: "{}", enabled: true}
          llb: {tag: B-12.0.R7, cpu: 6, memory: 16Gi, hugepages1Gi: 1Gi, nodeSelector: "{}", enabled: false, total: 3}
          nasc: {tag: B-12.0.R7, cpu: 100m, memory: 100Mi, enabled: true}
          logging: {tag: B-12.0.R7, cpu: 100m, memory: 100Mi, enabled: true}
          awsSideCar: {tag: B-12.0.R7, cpu: 100m, memory: 100Mi, enabled: false}
      amf:
        enabled: true
        namespace: amf
        storage_class: nfs-csi
        prometheus_ip: 192.168.5.14
        networking: 
          type: ipvlan
          # oam is mandatory, other networks can be renamed or deleted/added
          multus: {oam: multus-mgmt, 3GPP_External: multus-external, 3GPP_SBA: multus-sba}
        pods:
          dbs: {tag: CMM21.0.0P1, cpu: 4, memory: 8Gi, nodeSelector: "{}", antiaffinity: [dbs], initialDelaySeconds: 15, periodSeconds: 20, enabled: true}
          emms_amms: {tag: CMM21.0.0P1, cpu: 4, memory: 16Gi, nodeSelector: "{}", antiaffinity: [amms], initialDelaySeconds: 5, periodSeconds: 20, enabled: true}
          ipds: {tag: CMM21.0.0P1, cpu: 6, memory: 12Gi, nodeSelector: "{}", antiaffinity: [ipds], initialDelaySeconds: 30, periodSeconds: 20, enabled: true}
          ipps: {tag: CMM21.0.0P1, cpu: 8, memory: 12Gi, nodeSelector: "{}", antiaffinity: [], initialDelaySeconds: 30, periodSeconds: 20, enabled: false}
          necc: {tag: CMM21.0.0P1, cpu: 4, memory: 12Gi, nodeSelector: "{}", antiaffinity: [necc], initialDelaySeconds: 120, periodSeconds: 20, enabled: true}
          paps: {tag: CMM21.0.0P1, cpu: 4, memory: 12Gi, nodeSelector: "{}", antiaffinity: [], initialDelaySeconds: 30, periodSeconds: 20, enabled: false}

topology:
  kinds:
    srl:
      type: ixrd2
      position: network
    vr-sros:
      type: sr-1s
      position: network
    linux:
      type: rhel8
      labels: {"need_update_dist": false, "install_rt_sched": false, "install_net_driver": true} 
      position: access
      storage:
        nfs_server: 100.112.1.201
        nfs_mount: /nfs
        csi: nfs-csi
  nodes:
    leaf1:
      kind: srl
      mgmt_ipv4: 172.20.20.3
      labels: {"target": "leaf-grp1"}      
    leaf2:
      kind: srl
      mgmt_ipv4: 172.20.20.4
      labels: {"target": "leaf-grp1"} 
    master0:
      kind: linux
      mgmt_ipv4: 100.112.3.11
      labels: {"target": "servers"}
    worker0:
      kind: linux
      mgmt_ipv4: 100.112.3.12
      labels: {"target": "servers"}
    worker1:
      kind: linux
      mgmt_ipv4: 100.112.3.13
      labels: {"target": "servers"}
    worker2:
      kind: linux
      mgmt_ipv4: 100.112.3.14
      labels: {"target": "servers"}
    worker3:
      kind: linux
      mgmt_ipv4: 100.112.3.15
      labels: {"target": "servers"}
    dcgw1:
      kind: sros
      mgmt_ipv4: 172.20.20.1
      labels: {"target": "dcgw-grp1"}
    dcgw2:
      kind: sros
      mgmt_ipv4: 172.20.20.2
      labels: {"target": "dcgw-grp1"}

  links:
    # server connectivity
    - endpoints: ["leaf1:e1-1", "master0:eno5"]
      labels: {"kind": "access", "type": "esi1", "client-name": "bond0", "sriov": true, "ipvlan": true, "speed": "10G", "pxe": true}
    - endpoints: ["leaf2:e1-1", "master0:eno6"]
      labels: {"kind": "access", "type": "esi1", "client-name": "bond0", "sriov": true, "ipvlan": true, "speed": "10G"}
    - endpoints: ["leaf1:e1-2", "master0:ens2f0"]
      labels: {"kind": "access", "type": "esi2", "client-name": "bond1", "sriov": true, "ipvlan": true, "speed": "10G", "pxe": true}
    - endpoints: ["leaf2:e1-2", "master0:ens2f1"]
      labels: {"kind": "access", "type": "esi2", "client-name": "bond1", "sriov": true, "ipvlan": true, "speed": "10G"}
    # - endpoints: ["leaf1:e1-3", "worker0:eno5"]
    #   labels: {"kind": "access", "type": "esi3", "client-name": "bond0", "sriov": true, "ipvlan": true, "speed": "10G", "pxe": true}
    # - endpoints: ["leaf2:e1-3", "worker0:eno6"]
    #   labels: {"kind": "access", "type": "esi3", "client-name": "bond0", "sriov": true, "ipvlan": true, "speed": "10G"}
    # - endpoints: ["leaf1:e1-4", "worker0:ens2f0"]
    #   labels: {"kind": "access", "type": "esi4", "client-name": "bond1", "sriov": true, "ipvlan": true, "speed": "10G", "pxe": true}
    # - endpoints: ["leaf2:e1-4", "worker0:ens2f1"]
    #   labels: {"kind": "access", "type": "esi4", "client-name": "bond1", "sriov": true, "ipvlan": true, "speed": "10G"}
    # - endpoints: ["leaf1:e1-5", "worker1:eno5"]
    #   labels: {"kind": "access", "type": "esi5", "client-name": "bond0", "sriov": true, "ipvlan": true, "speed": "10G", "pxe": true}
    # - endpoints: ["leaf2:e1-5", "worker1:eno6"]
    #   labels: {"kind": "access", "type": "esi5", "client-name": "bond0", "sriov": true, "ipvlan": true, "speed": "10G"}
    # - endpoints: ["leaf1:e1-6", "worker1:ens2f0"]
    #   labels: {"kind": "access", "type": "esi6", "client-name": "bond1", "sriov": true, "ipvlan": true, "speed": "10G", "pxe": true}
    # - endpoints: ["leaf2:e1-6", "worker1:ens2f1"]
    #   labels: {"kind": "access", "type": "esi6", "client-name": "bond1", "sriov": true, "ipvlan": true, "speed": "10G"}
    # - endpoints: ["leaf1:e1-7", "worker2:eno5"]
    #   labels: {"kind": "access", "type": "esi7", "client-name": "bond0", "sriov": true, "ipvlan": true, "speed": "10G", "pxe": true}
    # - endpoints: ["leaf2:e1-7", "worker2:eno6"]
    #   labels: {"kind": "access", "type": "esi7", "client-name": "bond0", "sriov": true, "ipvlan": true, "speed": "10G"}
    # - endpoints: ["leaf1:e1-8", "worker2:ens2f0"]
    #   labels: {"kind": "access", "type": "esi8", "client-name": "bond1", "sriov": true, "ipvlan": true, "speed": "10G", "pxe": true}
    # - endpoints: ["leaf2:e1-8", "worker2:ens2f1"]
    #   labels: {"kind": "access", "type": "esi8", "client-name": "bond1", "sriov": true, "ipvlan": true, "speed": "10G"}
    # - endpoints: ["leaf1:e1-9", "worker3:eno5"]
    #   labels: {"kind": "access", "type": "esi9", "client-name": "bond0", "sriov": true, "ipvlan": true, "speed": "10G", "pxe": true}
    # - endpoints: ["leaf2:e1-9", "worker3:eno6"]
    #   labels: {"kind": "access", "type": "esi9", "client-name": "bond0", "sriov": true, "ipvlan": true, "speed": "10G"}
    # - endpoints: ["leaf1:e1-10", "worker3:ens2f0"]
    #   labels: {"kind": "access", "type": "esi10", "client-name": "bond1", "sriov": true, "ipvlan": true, "speed": "10G", "pxe": true}
    # - endpoints: ["leaf2:e1-10", "worker3:ens2f1"]
    #   labels: {"kind": "access", "type": "esi10", "client-name": "bond1", "sriov": true, "ipvlan": true, "speed": "10G"}
    # switch interconnect links
    - endpoints: ["leaf1:e1-49", "leaf2:e1-49"]
    # dcgw connectivity
    - endpoints: ["leaf1:e1-50", "dcgw1:eth1"]
      labels: {"kind": "access", "speed": "40G"}
    - endpoints: ["leaf2:e1-50", "dcgw2:eth1"]
      labels: {"kind": "access", "speed": "40G"}

